"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var descritorEmpresa_1 = require("./out/descritorEmpresa");
var empresa_1 = require("./out/empresa");
var endereco_1 = require("./out/endereco");
var funcionario_1 = require("./out/funcionario");
var telefone_1 = require("./out/telefone");
var enderecoEmpresa = new endereco_1.default(123, 'Av. Paulista', 'Jardim Paulista', 'São Paulo');
var telefoneEmpresa = new telefone_1.Telefone('11', '9-9999-9999');
var endereco1 = new endereco_1.default(456, 'Rua XV de Novembro', 'Centro', 'Rio de Janeiro');
var telefone1 = new telefone_1.Telefone('21', '9-8765-4321');
var funcionario1 = new funcionario_1.Funcionario('Maria Silva', '987654321', '111.222.333-44', endereco1, telefone1);
var endereco2 = new endereco_1.default(789, 'Rua dos Três Rios', 'Copacabana', 'Rio de Janeiro');
var telefone2 = new telefone_1.Telefone('21', '9-1234-5678');
var funcionario2 = new funcionario_1.Funcionario('Pedro Costa', '987654322', '555.666.777-88', endereco2, telefone2);
var funcionarios = [funcionario1, funcionario2];
var empresa = new empresa_1.Empresa('ABC LTDA', 'Mercado online', '999-999-999-999-99', enderecoEmpresa, telefoneEmpresa, funcionarios);
var descritor = new descritorEmpresa_1.Descritor(empresa);
console.log(descritor.descrever());
